version: '3.3'
services:
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - '/pgdata:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  mainapp:
    image: ${APP_IMAGE}
    restart: always
    depends_on:
      - postgres
    ports:
      - '80:80'
    env_file:
      - .env
    logging:
      options:
        max-size: 1g
    entrypoint: sh -c "bin/console cache:clear && bin/console doctrine:schema:update --force && php bin/index.php"
